export const DEFAULTS = {
  apiKey: "",
  model: "claude-opus-5",
  autoOrganize: true,
  intervalMinutes: 5,
  debounceSeconds: 8,
  sendPageText: true,
  collapseInactive: false,
  closeDuplicates: true,
  cleanupStale: true,
  staleDays: 3,
  obsidianEnabled: true,
  obsidianUrl: "http://127.0.0.1:27123",
  obsidianApiKey: "",
  digestEnabled: true,
  digestHour: 21,
  vaultFolders: "00-Inbox\n10-Areas\n20-Projects\n30-Resources",
  ignoredDomains: "",
  customInstructions: "",
};
